### ISSUE TITLE
Do I need to install Preact? 

### ISSUE THREAD

**Issue by ninja-pinky** [preactjs/preset-vite#55]
after installing "@preact/preset-vite" I test my code and it works without installing Preact, do I need to install Preact or "preact/preset-vite" is enough?

vite.config.js

```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import preact from "@preact/preset-vite";

export default defineConfig({
    plugins: [
        laravel([
            // 'resources/css/app.css',
            'resources/js/app-preact.js',
        ]),
        preact(),
    ],
});
```

App.js
```
import { Fragment, h, render } from 'preact'
import {useEffect, useState} from "preact/hooks";

function App()
{
	const [ city, setCity ] = useState('');
    return (
        <>
            <p>{city}</p>
            <button onClick={()=>setCity('Madrid')}>test</button>
        </>
    )
}

const el = document.getElementById('react-root')

if(el) {
  render(<App/>, el)
}
```

**Comment by marvinhagemeister** [comment]
It works because the package manager you're using (`npm`, `yarn` or `pnpm`) was nice enough to resolve the peer peerdendency for you, despite it not being listed as a dependency in your project. I'm very certain that they printed some yellow warnings during the installation process.

So yeah, it does work, but it's not recommended as you may end up with duplicate or multiple different preact versions in your app. These things are usually pretty hard to debug when that happens.

If you want to be sure that you're not running into edge cases with your package manager and want to ensure that your project keeps working in the future, I'd recommend adding `preact` as a dependency explicitly.
