### ISSUE TITLE
Compat alias not working for pnpm link project

### ISSUE THREAD

**Issue by jennydaman** [preactjs/preset-vite#94]
I am trying to create a React component library and use `pnpm link` to use it in a demo project. In the demo project, I am trying to use Preact (while the component library uses React). 

https://github.com/jennydaman/preact-vite-pnpm-link-bug

In this minimal reproduction case, I created some projects by running

```shell
pnpm create vite preact-demo --template preact-ts
pnpm create vite react-demo --template react-ts
```

I also created a third package which exports `ExampleComponent`:

```tsx
import React, { useState } from "react";

const ExampleComponent: React.FC = () => {
  const [counter, setCounter] = React.useState(0);
  return (<>
    <h1>this is ExampleComponent.</h1>
    <button onClick={() => setCounter(counter + 1)}>ExampleComponent counter: {counter}</button>
  </>)
}

export { ExampleComponent };
```

To `{preact,react}-demo/src/App.tsx` I added the code

```jsx
<ExampleComponent />
```

Then linked the projects:

```shell
cd preact-demo
pnpm install
pnpm link ../component

cd ../react-demo
pnpm install
pnpm link ../component
```

The `react-demo` works as-expected, however `preact-demo` fails:

```
[plugin:vite:import-analysis] Failed to resolve import "react" from "../niivue-react/src/NiivueCanvas.tsx". Does the file exist?
```

**Comment by rschristian** [comment]
Don't use symlinks to test libraries, that's full of unexpected and non-representative behaviors.

Use something like [`yalc`](https://npm.im/yalc) instead.

**Comment by rschristian** [comment]
Closing, let me know if you are still having issues and we can reopen/look into them.

**Comment by thegecko** [comment]
Hit the same issue. When using a `yarn linked` dependency, there are errors of the form:

[vite:load-fallback] Could not load preact/compat (imported by <SYMLINKED FOLDER>): ENOENT: no such file or directory, open 'preact/compat'

> Don't use symlinks to test libraries, that's full of unexpected and non-representative behaviors.

This is the first issue I've had with using link and its the built in way to undertake this in npm/yarn

**Comment by rschristian** [comment]
> its the built in way to undertake this in npm/yarn

Symlinks are unfortunately full of flaws in authoring libs. For example:

```
my-lib
--node_modules/
----preact@10.25.0
--src/
```

When you use `npm link` or `yarn link`, your library will use its `node_modules`, rather than the modules installed in your app. This will frequently cause issues due to unexpected versions being used and, in the case of Preact, completely breaks hooks as Preact will not be loaded as a singleton; your app will provide a version of Preact and another will be dragged through the symlink. Links also completely fail to acknowledge `"files"` or your `.npmrc`, so a link can appear to work only for a publish to be missing files.

This is something we've seen come up time and time again, just skip it and the headaches. `yalc`, linked above, essentially is a registry on your own machine that you can publish and install from, bypassing these issues as well as helping you catch mistakes.
